SELECT TOP (1000) [RowID]
      ,[OrderID]
      ,[OrderDate]
      ,[ShipDate]
      ,[ShipMode]
      ,[CustomerID]
      ,[CustomerName]
      ,[Segment]
      ,[Country]
      ,[City]
      ,[State]
      ,[PostalCode]
      ,[Region]
      ,[ProductID]
      ,[Category]
      ,[SubCategory]
      ,[ProductName]
      ,[Sales]
      ,[Quantity]
      ,[Discount]
      ,[Profit]
  FROM [SuperStore].[dbo].[Superstore]
